on:
  push:
    branches: ['**']

jobs:

  ctest:
    strategy:
      fail-fast: false
      matrix:
        runs_on: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.runs_on }}
    steps:
      - if: runner.os == 'Linux'
        run: sudo apt-get install -y ninja-build
      - if: runner.os == 'macOS'
        run: brew install ninja
      - uses: actions/checkout@v3
      - run: cmake --help
      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build
